import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  firstAnimatedView: (animateHeader: any, animateBackground: any) => ({
    width: "100%",
    position: "absolute",
    height: 150,
    zIndex: 999,
    alignItems: "center",
    borderBottomEndRadius: 20,
    borderBottomStartRadius: 20,
    justifyContent: "center",
    paddingHorizontal: 15,
    backgroundColor: animateBackground,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  }),
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  list: {
    paddingHorizontal: 5,
  },
  searchBar__unclicked: {
    padding: 10,
    flexDirection: "row",
    width: "95%",
    backgroundColor: "#d9dbda",
    borderRadius: 15,
    alignItems: "center",
  },
  searchBar__clicked: {
    padding: 10,
    flexDirection: "row",
    width: "80%",
    backgroundColor: "#d9dbda",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  input: {
    backgroundColor: "#fff",
    width: "100%",
    alignItems: "center",
    height: 47,
    paddingHorizontal: 10,
    borderRadius: 8,
    color: "#746B6B",
    borderColor: "#222",
    borderWidth: 0.4,
    fontFamily: "Poppins_400Regular",
  },
  userContainer: (headerDisplay: any) => ({
    width: "100%",
    marginBottom: 0,
    top: headerDisplay,
  }),
  userInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  font16: {
    fontSize: 16,
    fontWeight: "600",
    color: "#393939",
  },
  nameContext: {
    fontSize: 12,
    fontWeight: "400",
    color: "#a8a8a8",
    marginBottom: 1,
    marginTop: 7,
  },
  textUserType: {
    fontSize: 12,
    fontWeight: "400",
    color: "#a8a8a8",
  },
  userImageContainer: {
    width: "30%",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  imageUser: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: "#ccc",
  },
  inputSearch: (inputPosition: any) => ({
    width: "100%",
    justifyContent: "center",
    top: inputPosition,
  }),
  contentScroll: {
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 190,
    height: "100%",
    marginHorizontal: 16,
  },
  innerContainer: {
    width: "100%",
    height: "100%",
    paddingBottom: 10,
    marginTop: 8,
  },
  cardListContainer: {
    width: "100%",
    marginBottom: 34,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    borderRadius: 12,
    justifyContent: "center",
  },
  imageCardList: {
    width: "30%",
    height: "100%",
    padding: 5,
    justifyContent: "center",
  },
  rightContainerCardList: {
    width: "100%",
    height: "100%",
    paddingHorizontal: "10%",
    justifyContent: "center",
    alignItems: "center",
  },
  titleCardList: {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    textAlign: "center",
    marginBottom: 8,
  },
  titleCardListNotPremium: {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    textAlign: "center",
    padding: 20,
    marginTop: 16,
    backgroundColor: "#f5f5f5",
  },
  descriptionCardList: {
    fontSize: 11,
    fontFamily: "Poppins_400Regular",
  },
  buttonAcceptCardList: {
    width: "70%",
    height: 40,
    backgroundColor: "#000",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  textButtonCardList: {
    color: "#fff",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 11,
  },
  innerFlatlist: {
    paddingBottom: "100%",
    paddingHorizontal: 16,
    paddingTop: 2,
  },
  flatlist: {
    flex: 2,
    paddingTop: 10,
    marginHorizontal: -16,
  },
});

export default styles;
