import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  modal3: {
    height: 600,
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  modal: {
    alignItems: "center",
    zIndex: 99999999,
    borderRadius: 15,
  },
  modalBoxContainer: {
    width: "100%",
    height: 250,
    backgroundColor: "#fff",
    marginTop: 0,
    borderRadius: 15,
  },
  modalWelcome: {
    alignItems: "flex-start",
    justifyContent: "flex-start",
    padding: 15,
  },
  imageUserContainer: {
    width: "30%",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  imageBackground: {
    flex: 1,
    justifyContent: "center",
    top: 0,
    bottom: 0,
    width: "100%",
    height: 258,
  },
  continue: {
    backgroundColor: "#DDDDDD",
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  animatedHeader: (headerHeigth, isOpen, background) => ({
    width: "100%",
    display: isOpen ? "none" : "flex",
    position: "absolute",
    height: headerHeigth,
    zIndex: 88,
    alignItems: "center",
    borderBottomEndRadius: 20,
    borderBottomStartRadius: 20,
    justifyContent: "center",
    paddingHorizontal: 15,
    backgroundColor: background,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  }),
  innerAnimatedHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingVertical: 10,
  },
  locationText: {
    fontSize: 12,
    fontWeight: "400",
    color: "#a8a8a8",
    marginBottom: 1,
    marginTop: 7,
  },
  imageStyle: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: "#dedcdc",
  },
  scrollAnimated: {
    alignItems: "center",
    justifyContent: "flex-start",
    marginTop: 180,
    flex: 1,
  },
  welcomeContainer: {
    width: "100%",
    paddingVertical: 20,
    marginTop: 0,
    paddingHorizontal: 15,
  },
  modalBackground: {
    marginVertical: 20,
    width: "100%",
    height: 250,
    backgroundColor: "#fff",
    borderRadius: 5,
    shadowColor: "#393939",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    position: "relative",
  },
  imageBackgroundModal: {
    flex: 1,
    justifyContent: "center",
    top: 0,
    bottom: 0,
    width: 352,
    height: 258,
    borderRadius: 15,
  },
  connectBusinessContainer: {
    width: "70%",
    height: "100%",
    alignSelf: "flex-start",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  exploreContainer: {
    minWidth: 95,
    height: 25,
    backgroundColor: "#daf0fe",
    borderRadius: 55,
    top: 20,
    left: 20,
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
  },
  exploreText: {
    fontSize: 12,
    color: "#a7c4d8",
    fontWeight: "600",
  },
  yourPostsContainer: {
    width: "100%",
    marginVertical: 20,
    paddingHorizontal: 15,
  },
  welcomeModalContainer: (wid: number) => ({
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
    height: wid / 2.6,
    width: wid * 0.8 - 20,
    marginHorizontal: 10,
    padding: 10,
    borderRadius: 12,
    marginVertical: 20,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  }),
  publicateText: {
    fontSize: 15,
    fontFamily: "Poppins_500Medium",
    color: "#404040",
  },
  innerPublicateText: {
    fontSize: 11,
    fontFamily: "Poppins_400Regular",
    color: "#222",
    marginTop: 15,
  },
  statisticContainer: {
    padding: 20,
    marginTop: 50,
    backgroundColor: "#fff",
    justifyContent: "flex-end",
  },
  viewsContainer: {
    marginVertical: 40,
    backgroundColor: "#f5f5f5",
    padding: 20,
  },
  poppinsNormal14: {
    fontSize: 14,
    fontFamily: "Poppins_500Medium",
    marginVertical: 5,
  },
  workContainer: {
    width: "100%",
    minHeight: 400,
    backgroundColor: "#f5f5f5",
    borderRadius: 10,
    marginTop: 20,
    padding: 15,
  },
  innerWorkContainer: {
    width: "100%",
    padding: 15,
    justifyContent: "center",
    minHeight: 90,
    alignItems: "center",
  },
  poppins600n18: {
    fontSize: 18,
    fontFamily: "Poppins_600SemiBold",
  },
  detailsContainer: {
    width: "100%",
    marginTop: 40,
    minHeight: 180,
    borderRadius: 12,
    padding: 10,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2.51,
    elevation: 2,
    justifyContent: "center",
  },
  poppinsBold14: {
    fontFamily: "Poppins_600SemiBold",
    fontSize: 14,
    color: "#393939",
  },
  poppinsMedium13: {
    fontFamily: "Poppins_500Medium",
    color: "#393939",
    fontSize: 13,
  },
  poppinsBold11: {
    fontFamily: "Poppins_600SemiBold",
    color: "#a8a8a8",
    fontSize: 11,
  },
  stopPostContainer: {
    width: "100%",
    padding: 20,
    backgroundColor: "#ede56d",
    elevation: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  removePostContainer: {
    width: "100%",
    padding: 20,
    marginTop: 30,
    backgroundColor: "#e06363",
    elevation: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  moreText: {
    color: "#689aaa",
    fontSize: 15,
    fontWeight: "700",
  },
  notAddedWorks: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  notAddedText: {
    fontSize: 17,
    fontFamily: "Poppins_500Medium",
    color: "#a8a8a8",
    marginTop: 8,
  },
  button: {
    height: 40,
    borderRadius: 8,
    marginTop: 10,
    width: "80%",
    alignSelf: "center",
  },
  labelButtonStyle: {
    lineHeight: 23,
    fontFamily: "Poppins_500Medium",
    fontSize: 18,
    color: "white",
  },
});

export default styles;
